"""
make_variants.py - build example reconfigurations of the baseline line by editing
RELATIONSHIPS only (no simulator code changes), and save them as YAML files that the
dashboard picks up automatically from configs/variants/.

    python examples/make_variants.py
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from line_sim import config_model as cm  # noqa: E402

CFG_DIR = ROOT / "configs"
OUT = CFG_DIR / "variants"
OUT.mkdir(parents=True, exist_ok=True)

base = cm.load_yaml_file(CFG_DIR / "line_config.yaml")


def save(cfg, name, title, msgs):
    cfg = cm.set_version(cfg, name, title)
    rep = cm.validate(cfg)
    assert rep.ok, rep.errors
    header = (f"Variant '{name}' - generated by examples/make_variants.py from line_config.yaml\n"
              f"{title}\n\nRelationship changes applied:\n" + "\n".join(f"  - {m}" for m in msgs))
    (OUT / f"{name}.yaml").write_text(cm.dump_yaml(cfg, header=header), encoding="utf-8")
    print(f"{name}: {rep.summary()}")
    for m in msgs:
        print("   ", m)


# 1) Move P3 from S3 to S2 (the document's example) - rebalances the S3 bottleneck.
cfg, msgs = cm.move_process(base, "P3", "S2", move_bins=True)
save(cfg, "rebalance_P3_to_S2",
     "Process P3 (bearing & shim install) moved from Station 3 to Station 2 to rebalance the line.", msgs)

# 2) Alternate bearing supplier: LC_35 -> B35 now contains C21 instead of C10.
cfg, m1 = cm.set_bin_component(base, "B35", "C21")
cfg, m2 = cm.replace_process_input(cfg, "P3", "C10", "C21")
save(cfg, "alt_bearing_C21",
     "Bin B35 (load cell LC_35) is re-stocked with C21, the alternate-supplier bearing, and P3 uses it.", m1 + m2)

# 3) Parallel alignment station: a second Station 3 (S3B) with its own operator, bins, load cells, camera.
cfg, msgs = cm.add_parallel_station(base, "S3", "S3B", operator="O7")
save(cfg, "parallel_S3", "A parallel twin of Station 3 (S3B) doubles capacity at the bottleneck.", msgs)

# 4) One operator shared by Stations 5 and 6 (operator O6 freed).
cfg, msgs = cm.set_station_operator(base, "S6", "O5")
save(cfg, "shared_operator_S5_S6", "Operator O5 runs both Station 5 and Station 6.", msgs)

# 5) Larger buffers everywhere.
cfg, msgs = base, []
for k in range(5):
    cfg, m = cm.set_buffer_capacity(cfg, k, 4)
    msgs += m
save(cfg, "big_buffers", "All buffers enlarged to 4 units.", msgs)
